In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Creating a list of forecasted dates from 1/1/2025-7/15/2025
date_list = pd.date_range(start='2025-01-01', end='2025-07-15', freq='D')
for date in date_list:
    print(f"Processing data for {date.strftime('%Y%m%d')}")

Processing data for 20250101
Processing data for 20250102
Processing data for 20250103
Processing data for 20250104
Processing data for 20250105
Processing data for 20250106
Processing data for 20250107
Processing data for 20250108
Processing data for 20250109
Processing data for 20250110
Processing data for 20250111
Processing data for 20250112
Processing data for 20250113
Processing data for 20250114
Processing data for 20250115
Processing data for 20250116
Processing data for 20250117
Processing data for 20250118
Processing data for 20250119
Processing data for 20250120
Processing data for 20250121
Processing data for 20250122
Processing data for 20250123
Processing data for 20250124
Processing data for 20250125
Processing data for 20250126
Processing data for 20250127
Processing data for 20250128
Processing data for 20250129
Processing data for 20250130
Processing data for 20250131
Processing data for 20250201
Processing data for 20250202
Processing data for 20250203
Processing data for 20250204
Processing data for 20250205
Processing data for 20250206
Processing data for 20250207
Processing data for 20250208
Processing data for 20250209
Processing data for 20250210
Processing data for 20250211
Processing data for 20250212
Processing data for 20250213
Processing data for 20250214
Processing data for 20250215
Processing data for 20250216
Processing data for 20250217
Processing data for 20250218
Processing data for 20250219
Processing data for 20250220
Processing data for 20250221
Processing data for 20250222
Processing data for 20250223
Processing data for 20250224
Processing data for 20250225
Processing data for 20250226
Processing data for 20250227
Processing data for 20250228
Processing data for 20250301
Processing data for 20250302
Processing data for 20250303
Processing data for 20250304
Processing data for 20250305
Processing data for 20250306
Processing data for 20250307
Processing data for 20250308
Processing data for 20250309
Processing data for 20250310
Processing data for 20250311
Processing data for 20250312
Processing data for 20250313
Processing data for 20250314
Processing data for 20250315
Processing data for 20250316
Processing data for 20250317
Processing data for 20250318
Processing data for 20250319
Processing data for 20250320
Processing data for 20250321
Processing data for 20250322
Processing data for 20250323
Processing data for 20250324
Processing data for 20250325
Processing data for 20250326
Processing data for 20250327
Processing data for 20250328
Processing data for 20250329
Processing data for 20250330
Processing data for 20250331
Processing data for 20250401
Processing data for 20250402
Processing data for 20250403
Processing data for 20250404
Processing data for 20250405
Processing data for 20250406
Processing data for 20250407
Processing data for 20250408
Processing data for 20250409
Processing data for 20250410
Processing data for 20250411
Processing data for 20250412
Processing data for 20250413
Processing data for 20250414
Processing data for 20250415
Processing data for 20250416
Processing data for 20250417
Processing data for 20250418
Processing data for 20250419
Processing data for 20250420
Processing data for 20250421
Processing data for 20250422
Processing data for 20250423
Processing data for 20250424
Processing data for 20250425
Processing data for 20250426
Processing data for 20250427
Processing data for 20250428
Processing data for 20250429
Processing data for 20250430
Processing data for 20250501
Processing data for 20250502
Processing data for 20250503
Processing data for 20250504
Processing data for 20250505
Processing data for 20250506
Processing data for 20250507
Processing data for 20250508
Processing data for 20250509
Processing data for 20250510
Processing data for 20250511
Processing data for 20250512
Processing data for 20250513
Processing data for 20250514
Processing data for 20250515
Processing data for 20250516
Processing data for 20250517
Processing data for 20250518
Processing data for 20250519
Processing data for 20250520
Processing data for 20250521
Processing data for 20250522
Processing data for 20250523
Processing data for 20250524
Processing data for 20250525
Processing data for 20250526
Processing data for 20250527
Processing data for 20250528
Processing data for 20250529
Processing data for 20250530
Processing data for 20250531
Processing data for 20250601
Processing data for 20250602
Processing data for 20250603
Processing data for 20250604
Processing data for 20250605
Processing data for 20250606
Processing data for 20250607
Processing data for 20250608
Processing data for 20250609
Processing data for 20250610
Processing data for 20250611
Processing data for 20250612
Processing data for 20250613
Processing data for 20250614
Processing data for 20250615
Processing data for 20250616
Processing data for 20250617
Processing data for 20250618
Processing data for 20250619
Processing data for 20250620
Processing data for 20250621
Processing data for 20250622
Processing data for 20250623
Processing data for 20250624
Processing data for 20250625
Processing data for 20250626
Processing data for 20250627
Processing data for 20250628
Processing data for 20250629
Processing data for 20250630
Processing data for 20250701
Processing data for 20250702
Processing data for 20250703
Processing data for 20250704
Processing data for 20250705
Processing data for 20250706
Processing data for 20250707
Processing data for 20250708
Processing data for 20250709
Processing data for 20250710
Processing data for 20250711
Processing data for 20250712
Processing data for 20250713
Processing data for 20250714
Processing data for 20250715

In [3]:
# loop through bulk forecast
bulktrans_df = pd.DataFrame()
for date in date_list:
    file_path = f'//sce.eix.com/workgroup/SPE_DSA/Charles/IgnitionGoalSettingInput/Bulk_Forecasts 1-1-25 through 7-15-25/circuit_level_weather_fpi2_BulkTrans_HFA_{date.strftime("%Y%m%d")}.csv'
    try:
        df = pd.read_csv(file_path)
        df['Date'] = date.strftime('%Y-%m-%d')
        bulktrans_df = pd.concat([bulktrans_df, df], ignore_index=True)
    except FileNotFoundError:
        print(f"File not found: {file_path}")

In [4]:
### Loop through all forecasted distribution circuits files
dist_df = pd.DataFrame()
for date in date_list:
    file_path = f'//sce.eix.com/workgroup/SPE_DSA/Charles/IgnitionGoalSettingInput/Dist_Forecasts 1-1-25 through 7-15-25/circuit_level_weather_fpi2_Distribution_HFA_{date.strftime("%Y%m%d")}.csv'
    # try reading file_path if possible and concat to result Dataframe
    try:
        df = pd.read_csv(file_path)
        df['Date'] = date.strftime('%Y-%m-%d')
        dist_df = pd.concat([dist_df, df], ignore_index=True)
    # if file does not exist, use the most recent date's file and get the new date from there
    except FileNotFoundError:
        print(f"File not found: {file_path}")
dist_df = dist_df[pd.to_datetime(dist_df['Datetime']).dt.year == 2025]
dist_df

,Datetime,Circuit,Circuit_No,District,County,Substation,Voltage,Wind_Threshold,Gust_Threshold,Wind_99_percentile,...,DFM1hr_max_FPI2,DFM10hr_max_FPI2,DFM100hr_max_FPI2,DFM1000hr_max_FPI2,LFM_max_FPI2,NDVI_max_FPI2,FuelsIndex_max_FPI2,LFPwtdd_max_FPI2,FPI2_Thresholds,Date
4,2025-01-01 00:00:00,ABACUS,5,31,San Bernardino,HIGHLAND,12.0,31.0,46.0,35.91,...,0.10,0.10,0.14,0.14,0.68,0.32,0.45,1.28,NaN,2025-01-01
5,2025-01-01 03:00:00,ABACUS,5,31,San Bernardino,HIGHLAND,12.0,31.0,46.0,35.91,...,0.09,0.10,0.14,0.14,0.68,0.32,0.45,1.52,NaN,2025-01-01
6,2025-01-01 06:00:00,ABACUS,5,31,San Bernardino,HIGHLAND,12.0,31.0,46.0,35.91,...,0.09,0.10,0.14,0.15,0.67,0.33,0.42,0.10,NaN,2025-01-01
7,2025-01-01 09:00:00,ABACUS,5,31,San Bernardino,HIGHLAND,12.0,31.0,46.0,35.91,...,0.08,0.09,0.13,0.13,0.68,0.32,0.48,0.21,NaN,2025-01-01
8,2025-01-01 12:00:00,ABACUS,5,31,San Bernardino,HIGHLAND,12.0,31.0,46.0,35.91,...,0.06,0.08,0.12,0.13,0.68,0.32,0.51,0.49,NaN,2025-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12604018,2025-07-21 12:00:00,ZONE,19850,35,Ventura,MOORPARK,16.0,40.0,58.0,33.78,...,0.11,0.12,0.19,0.11,0.68,0.25,0.85,1.67,NaN,2025-07-15
12604019,2025-07-21 15:00:00,ZONE,19850,35,Ventura,MOORPARK,16.0,40.0,58.0,33.78,...,0.10,0.11,0.18,0.11,0.68,0.25,0.86,2.57,NaN,2025-07-15
12604020,2025-07-21 18:00:00,ZONE,19850,35,Ventura,MOORPARK,16.0,40.0,58.0,33.78,...,0.09,0.09,0.18,0.11,0.68,0.25,0.87,1.91,NaN,2025-07-15
12604021,2025-07-21 21:00:00,ZONE,19850,35,Ventura,MOORPARK,16.0,40.0,58.0,33.78,...,0.12,0.09,0.17,0.11,0.68,0.25,0.86,0.41,NaN,2025-07-15
12604022,2025-07-22 00:00:00,ZONE,19850,35,Ventura,MOORPARK,16.0,40.0,58.0,33.78,...,0.18,0.12,0.18,0.12,0.66,0.26,0.83,0.01,NaN,2025-07-15

In [5]:
# loop through sub forecast
sub_df = pd.DataFrame()
for date in date_list:
    file_path = f'//sce.eix.com/workgroup/SPE_DSA/Charles/IgnitionGoalSettingInput/Sub_Forecasts 1-1-25 through 7-15-25/circuit_level_weather_fpi2_SubTrans_HFA_{date.strftime("%Y%m%d")}.csv'
    try:
        df = pd.read_csv(file_path)
        df['Date'] = date.strftime('%Y-%m-%d')
        sub_df = pd.concat([sub_df, df], ignore_index=True)
    except FileNotFoundError:
        print(f"File not found: {file_path}")

In [6]:
# cols_to_keep_trans = ['Datetime','Master Circuit','FuelsIndex_max_FPI2','LFPwtdd_max_FPI2']
# cols_to_keep_dist = ['Datetime','Circuit','FuelsIndex_max_FPI2','LFPwtdd_max_FPI2']
# forecast_circuit_2025 = pd.concat([bulktrans_df[cols_to_keep_trans].rename(columns={'Master Circuit':'Circuit Name'}), 
#                                    dist_df[cols_to_keep_dist].rename(columns={'Circuit': 'Circuit Name'}), 
#                                    sub_df[cols_to_keep_trans].rename(columns={'Master Circuit':'Circuit Name'})], ignore_index=True)
# # Convert 'Datetime' to datetime type
# forecast_circuit_2025['Datetime'] = pd.to_datetime(forecast_circuit_2025['Datetime'])
# # make sure only 2025 data is kept
# forecast_circuit_2025 = forecast_circuit_2025[forecast_circuit_2025['Datetime'].dt.year == 2025]
# # rename columns
# forecast_circuit_2025 = forecast_circuit_2025.rename(columns={
#     'FuelsIndex_max_FPI2': 'max_max_fpi_2.0_tdd_fuels_index',
#     'LFPwtdd_max_FPI2': 'max_max_lfpw_using_dew_point_depression'
# },)
# # create a string Date column
# forecast_circuit_2025['Date'] = forecast_circuit_2025['Datetime'].dt.strftime('%Y-%m-%d')
# # group by Date, Circuit Name, and Circuit_No, set max_max_fpi_2.0_tdd_fuels_index and max_max_lfpw_using_dew_point_depression to the max value
# forecast_circuit_2025 = forecast_circuit_2025.groupby(['Date', 'Circuit Name', ]).agg({
#     'max_max_fpi_2.0_tdd_fuels_index': 'max',
#     'max_max_lfpw_using_dew_point_depression': 'max'
# }).reset_index()

In [7]:
# create a list of Date ranges from 07-07 to today date
today = pd.to_datetime("today").strftime("%Y-%m-%d")
date_ranges = pd.date_range(start='2025-07-16', end=today)
# create a list of valid dates
valid_dates = ['07-16-2025']
# create an empty dataframe for forecast data
forecast_file_group = pd.DataFrame()
# loop through date ranges
for date in date_ranges:
    # try to read the forecast file
    try:
        print(date.strftime('%m-%d-%Y'))
        forecast_file = pd.read_csv(f"//sce.eix.com/workgroup/SPE_DSA/Charles/ADS_forecast/Dist Circuit FPI2 Forecast_{date.strftime('%m-%d-%Y')}.csv",)
        # make sure date is in string format
        forecast_file['Date'] = pd.to_datetime(forecast_file['Datetime']).dt.strftime('%Y-%m-%d')
        # keep only current date
        forecast_file = forecast_file[forecast_file['Date'] == date.strftime('%Y-%m-%d')]
        # append to forecast_file_group
        forecast_file_group = pd.concat([forecast_file_group, forecast_file], ignore_index=True)
        # add date to valid dates
        valid_dates.append(date.strftime('%m-%d-%Y'))
    except:
        print(f"File for {date.strftime('%m-%d-%Y')} not found, using previous valid date instead...")
        forecast_file = pd.read_csv(f"//sce.eix.com/workgroup/SPE_DSA/Charles/ADS_forecast/Dist Circuit FPI2 Forecast_{valid_dates[-1]}.csv",)
        # make sure date is in string format
        forecast_file['Date'] = pd.to_datetime(forecast_file['Datetime']).dt.strftime('%Y-%m-%d')
        # keep only current date
        forecast_file = forecast_file[forecast_file['Date'] == date.strftime('%Y-%m-%d')]
        # append to forecast_file_group
        forecast_file_group = pd.concat([forecast_file_group, forecast_file], ignore_index=True)
# sort by Circuit and Date
forecast_file_group = forecast_file_group.sort_values(by=['Circuit','Datetime']).reset_index(drop=True)

07-16-2025
07-17-2025
File for 07-17-2025 not found, using previous valid date instead...
07-18-2025
07-19-2025
File for 07-19-2025 not found, using previous valid date instead...
07-20-2025
File for 07-20-2025 not found, using previous valid date instead...
07-21-2025
07-22-2025
07-23-2025
File for 07-23-2025 not found, using previous valid date instead...
07-24-2025
07-25-2025
07-26-2025
File for 07-26-2025 not found, using previous valid date instead...
07-27-2025
File for 07-27-2025 not found, using previous valid date instead...
07-28-2025
07-29-2025
07-30-2025
07-31-2025
08-01-2025
File for 08-01-2025 not found, using previous valid date instead...
08-02-2025
08-03-2025
File for 08-03-2025 not found, using previous valid date instead...
08-04-2025
08-05-2025
08-06-2025
File for 08-06-2025 not found, using previous valid date instead...
08-07-2025
08-08-2025
08-09-2025
File for 08-09-2025 not found, using previous valid date instead...
08-10-2025
File for 08-10-2025 not found, using previous valid date instead...
08-11-2025
08-12-2025
08-13-2025
08-14-2025
08-15-2025
08-16-2025
File for 08-16-2025 not found, using previous valid date instead...
08-17-2025
File for 08-17-2025 not found, using previous valid date instead...
08-18-2025
08-19-2025
08-20-2025
08-21-2025
08-22-2025
08-23-2025
File for 08-23-2025 not found, using previous valid date instead...
08-24-2025
File for 08-24-2025 not found, using previous valid date instead...
08-25-2025
File for 08-25-2025 not found, using previous valid date instead...
08-26-2025
08-27-2025
08-28-2025
08-29-2025
File for 08-29-2025 not found, using previous valid date instead...
08-30-2025
08-31-2025
File for 08-31-2025 not found, using previous valid date instead...
09-01-2025
File for 09-01-2025 not found, using previous valid date instead...
09-02-2025
09-03-2025
09-04-2025
09-05-2025
09-06-2025
09-07-2025
09-08-2025
09-09-2025
09-10-2025
09-11-2025
09-12-2025
09-13-2025
09-14-2025
09-15-2025
09-16-2025
09-17-2025
09-18-2025
09-19-2025
09-20-2025
09-21-2025
09-22-2025
09-23-2025
09-24-2025
09-25-2025
09-26-2025
09-27-2025
09-28-2025
09-29-2025
09-30-2025
10-01-2025
10-02-2025
10-03-2025
10-04-2025
10-05-2025
10-06-2025
10-07-2025
10-08-2025
10-09-2025
10-10-2025
10-11-2025
10-12-2025
10-13-2025
10-14-2025
10-15-2025
10-16-2025
10-17-2025
10-18-2025
10-19-2025
10-20-2025
File for 10-20-2025 not found, using previous valid date instead...
10-21-2025
10-22-2025
10-23-2025
10-24-2025
10-25-2025
10-26-2025
10-27-2025
10-28-2025
10-29-2025
10-30-2025
10-31-2025
File for 10-31-2025 not found, using previous valid date instead...
11-01-2025
File for 11-01-2025 not found, using previous valid date instead...
11-02-2025
11-03-2025
11-04-2025
11-05-2025
11-06-2025
11-07-2025
11-08-2025
11-09-2025
11-10-2025

### BulkTrans Section

In [8]:
# create a list of Date ranges from 07-07 to today date
today = pd.to_datetime("today").strftime("%Y-%m-%d")
date_ranges = pd.date_range(start='2025-07-16', end=today)
# create a list of valid dates
valid_dates = ['07-16-2025']
# create an empty dataframe for forecast data
forecast_file_group_bulktrans = pd.DataFrame()
# loop through date ranges
for date in date_ranges:
    # try to read the forecast file
    try:
        print(date.strftime('%m-%d-%Y'))
        forecast_file = pd.read_csv(f"//sce.eix.com/workgroup/SPE_DSA/Charles/ADS_forecast/BulkTrans Circuit FPI2 Forecast_{date.strftime('%m-%d-%Y')}.csv",)
        # make sure date is in string format
        forecast_file['Date'] = pd.to_datetime(forecast_file['Datetime']).dt.strftime('%Y-%m-%d')
        # keep only current date
        forecast_file = forecast_file[forecast_file['Date'] == date.strftime('%Y-%m-%d')]
        # append to forecast_file_group
        forecast_file_group_bulktrans = pd.concat([forecast_file_group_bulktrans, forecast_file], ignore_index=True)
        # add date to valid dates
        valid_dates.append(date.strftime('%m-%d-%Y'))
    except:
        print(f"File for {date.strftime('%m-%d-%Y')} not found, using previous valid date instead...")
        forecast_file = pd.read_csv(f"//sce.eix.com/workgroup/SPE_DSA/Charles/ADS_forecast/BulkTrans Circuit FPI2 Forecast_{valid_dates[-1]}.csv",)
        # make sure date is in string format
        forecast_file['Date'] = pd.to_datetime(forecast_file['Datetime']).dt.strftime('%Y-%m-%d')
        # keep only current date
        forecast_file = forecast_file[forecast_file['Date'] == date.strftime('%Y-%m-%d')]
        # append to forecast_file_group
        forecast_file_group_bulktrans = pd.concat([forecast_file_group_bulktrans, forecast_file], ignore_index=True)
# sort by Circuit and Date
forecast_file_group_bulktrans = forecast_file_group_bulktrans.sort_values(by=['Circuit','Datetime']).reset_index(drop=True)

07-16-2025
07-17-2025
File for 07-17-2025 not found, using previous valid date instead...
07-18-2025
07-19-2025
File for 07-19-2025 not found, using previous valid date instead...
07-20-2025
File for 07-20-2025 not found, using previous valid date instead...
07-21-2025
07-22-2025
07-23-2025
File for 07-23-2025 not found, using previous valid date instead...
07-24-2025
07-25-2025
07-26-2025
File for 07-26-2025 not found, using previous valid date instead...
07-27-2025
File for 07-27-2025 not found, using previous valid date instead...
07-28-2025
07-29-2025
07-30-2025
07-31-2025
08-01-2025
File for 08-01-2025 not found, using previous valid date instead...
08-02-2025
08-03-2025
File for 08-03-2025 not found, using previous valid date instead...
08-04-2025
08-05-2025
08-06-2025
File for 08-06-2025 not found, using previous valid date instead...
08-07-2025
08-08-2025
08-09-2025
File for 08-09-2025 not found, using previous valid date instead...
08-10-2025
File for 08-10-2025 not found, using previous valid date instead...
08-11-2025
08-12-2025
08-13-2025
08-14-2025
08-15-2025
08-16-2025
File for 08-16-2025 not found, using previous valid date instead...
08-17-2025
File for 08-17-2025 not found, using previous valid date instead...
08-18-2025
08-19-2025
08-20-2025
08-21-2025
08-22-2025
08-23-2025
File for 08-23-2025 not found, using previous valid date instead...
08-24-2025
File for 08-24-2025 not found, using previous valid date instead...
08-25-2025
File for 08-25-2025 not found, using previous valid date instead...
08-26-2025
08-27-2025
08-28-2025
08-29-2025
File for 08-29-2025 not found, using previous valid date instead...
08-30-2025
08-31-2025
File for 08-31-2025 not found, using previous valid date instead...
09-01-2025
File for 09-01-2025 not found, using previous valid date instead...
09-02-2025
09-03-2025
09-04-2025
09-05-2025
09-06-2025
09-07-2025
09-08-2025
09-09-2025
09-10-2025
09-11-2025
09-12-2025
09-13-2025
09-14-2025
09-15-2025
09-16-2025
09-17-2025
09-18-2025
09-19-2025
09-20-2025
09-21-2025
09-22-2025
09-23-2025
09-24-2025
09-25-2025
09-26-2025
09-27-2025
09-28-2025
09-29-2025
09-30-2025
10-01-2025
10-02-2025
10-03-2025
10-04-2025
10-05-2025
10-06-2025
10-07-2025
10-08-2025
10-09-2025
10-10-2025
10-11-2025
10-12-2025
10-13-2025
10-14-2025
10-15-2025
10-16-2025
10-17-2025
10-18-2025
10-19-2025
10-20-2025
File for 10-20-2025 not found, using previous valid date instead...
10-21-2025
10-22-2025
10-23-2025
10-24-2025
10-25-2025
10-26-2025
10-27-2025
10-28-2025
10-29-2025
10-30-2025
10-31-2025
File for 10-31-2025 not found, using previous valid date instead...
11-01-2025
File for 11-01-2025 not found, using previous valid date instead...
11-02-2025
11-03-2025
11-04-2025
11-05-2025
11-06-2025
11-07-2025
11-08-2025
11-09-2025
11-10-2025

### SubTrans Section

In [9]:
# create a list of Date ranges from 07-07 to today date
today = pd.to_datetime("today").strftime("%Y-%m-%d")
date_ranges = pd.date_range(start='2025-07-16', end=today)
# create a list of valid dates
valid_dates = ['07-16-2025']
# create an empty dataframe for forecast data
forecast_file_group_subtrans = pd.DataFrame()
# loop through date ranges
for date in date_ranges:
    # try to read the forecast file
    try:
        print(date.strftime('%m-%d-%Y'))
        forecast_file = pd.read_csv(f"//sce.eix.com/workgroup/SPE_DSA/Charles/ADS_forecast/BulkTrans Circuit FPI2 Forecast_{date.strftime('%m-%d-%Y')}.csv",)
        # make sure date is in string format
        forecast_file['Date'] = pd.to_datetime(forecast_file['Datetime']).dt.strftime('%Y-%m-%d')
        # keep only current date
        forecast_file = forecast_file[forecast_file['Date'] == date.strftime('%Y-%m-%d')]
        # append to forecast_file_group
        forecast_file_group_subtrans = pd.concat([forecast_file_group_subtrans, forecast_file], ignore_index=True)
        # add date to valid dates
        valid_dates.append(date.strftime('%m-%d-%Y'))
    except:
        print(f"File for {date.strftime('%m-%d-%Y')} not found, using previous valid date instead...")
        forecast_file = pd.read_csv(f"//sce.eix.com/workgroup/SPE_DSA/Charles/ADS_forecast/BulkTrans Circuit FPI2 Forecast_{valid_dates[-1]}.csv",)
        # make sure date is in string format
        forecast_file['Date'] = pd.to_datetime(forecast_file['Datetime']).dt.strftime('%Y-%m-%d')
        # keep only current date
        forecast_file = forecast_file[forecast_file['Date'] == date.strftime('%Y-%m-%d')]
        # append to forecast_file_group
        forecast_file_group_subtrans = pd.concat([forecast_file_group_subtrans, forecast_file], ignore_index=True)
# sort by Circuit and Date
forecast_file_group_subtrans = forecast_file_group_subtrans.sort_values(by=['Circuit','Datetime']).reset_index(drop=True)

07-16-2025
07-17-2025
File for 07-17-2025 not found, using previous valid date instead...
07-18-2025
07-19-2025
File for 07-19-2025 not found, using previous valid date instead...
07-20-2025
File for 07-20-2025 not found, using previous valid date instead...
07-21-2025
07-22-2025
07-23-2025
File for 07-23-2025 not found, using previous valid date instead...
07-24-2025
07-25-2025
07-26-2025
File for 07-26-2025 not found, using previous valid date instead...
07-27-2025
File for 07-27-2025 not found, using previous valid date instead...
07-28-2025
07-29-2025
07-30-2025
07-31-2025
08-01-2025
File for 08-01-2025 not found, using previous valid date instead...
08-02-2025
08-03-2025
File for 08-03-2025 not found, using previous valid date instead...
08-04-2025
08-05-2025
08-06-2025
File for 08-06-2025 not found, using previous valid date instead...
08-07-2025
08-08-2025
08-09-2025
File for 08-09-2025 not found, using previous valid date instead...
08-10-2025
File for 08-10-2025 not found, using previous valid date instead...
08-11-2025
08-12-2025
08-13-2025
08-14-2025
08-15-2025
08-16-2025
File for 08-16-2025 not found, using previous valid date instead...
08-17-2025
File for 08-17-2025 not found, using previous valid date instead...
08-18-2025
08-19-2025
08-20-2025
08-21-2025
08-22-2025
08-23-2025
File for 08-23-2025 not found, using previous valid date instead...
08-24-2025
File for 08-24-2025 not found, using previous valid date instead...
08-25-2025
File for 08-25-2025 not found, using previous valid date instead...
08-26-2025
08-27-2025
08-28-2025
08-29-2025
File for 08-29-2025 not found, using previous valid date instead...
08-30-2025
08-31-2025
File for 08-31-2025 not found, using previous valid date instead...
09-01-2025
File for 09-01-2025 not found, using previous valid date instead...
09-02-2025
09-03-2025
09-04-2025
09-05-2025
09-06-2025
09-07-2025
09-08-2025
09-09-2025
09-10-2025
09-11-2025
09-12-2025
09-13-2025
09-14-2025
09-15-2025
09-16-2025
09-17-2025
09-18-2025
09-19-2025
09-20-2025
09-21-2025
09-22-2025
09-23-2025
09-24-2025
09-25-2025
09-26-2025
09-27-2025
09-28-2025
09-29-2025
09-30-2025
10-01-2025
10-02-2025
10-03-2025
10-04-2025
10-05-2025
10-06-2025
10-07-2025
10-08-2025
10-09-2025
10-10-2025
10-11-2025
10-12-2025
10-13-2025
10-14-2025
10-15-2025
10-16-2025
10-17-2025
10-18-2025
10-19-2025
10-20-2025
File for 10-20-2025 not found, using previous valid date instead...
10-21-2025
10-22-2025
10-23-2025
10-24-2025
10-25-2025
10-26-2025
10-27-2025
10-28-2025
10-29-2025
10-30-2025
10-31-2025
File for 10-31-2025 not found, using previous valid date instead...
11-01-2025
File for 11-01-2025 not found, using previous valid date instead...
11-02-2025
11-03-2025
11-04-2025
11-05-2025
11-06-2025
11-07-2025
11-08-2025
11-09-2025
11-10-2025

### Save to Files

In [10]:
# create cols to keep for distribution circuits
cols_to_keep_dist = ['Datetime','Date','Circuit', 'FuelsIndex_max_FPI2', 'LFPwtdd_max_FPI2','Max_Wind','Max_Gust']
# concat dist_df with forecast_file_group
dist_df_with_forecast = pd.concat([dist_df[cols_to_keep_dist], forecast_file_group[cols_to_keep_dist]], ignore_index=True)
# save file to Distribution_Forecast_2025.csv
dist_df_with_forecast.to_csv('//sce.eix.com/workgroup/SPE_DSA/Charles/IgnitionGoalSettingMidput/Dist_Forecasts_2025.csv', index=False)

In [11]:
dist_df_with_forecast

,Datetime,Date,Circuit,FuelsIndex_max_FPI2,LFPwtdd_max_FPI2,Max_Wind,Max_Gust
0,2025-01-01 00:00:00,2025-01-01,ABACUS,0.45,1.28,6.51,7.40
1,2025-01-01 03:00:00,2025-01-01,ABACUS,0.45,1.52,6.75,7.72
2,2025-01-01 06:00:00,2025-01-01,ABACUS,0.42,0.10,1.66,1.73
3,2025-01-01 09:00:00,2025-01-01,ABACUS,0.48,0.21,2.37,2.49
4,2025-01-01 12:00:00,2025-01-01,ABACUS,0.51,0.49,3.18,4.55
...,...,...,...,...,...,...,...
13697590,2025-11-10 09:00:00,2025-11-10,ZONE,0.69,14.71,17.85,29.25
13697591,2025-11-10 12:00:00,2025-11-10,ZONE,0.72,8.02,12.09,20.71
13697592,2025-11-10 15:00:00,2025-11-10,ZONE,0.60,2.72,9.18,16.03
13697593,2025-11-10 18:00:00,2025-11-10,ZONE,0.59,1.12,6.97,10.89
13697594,2025-11-10 21:00:00,2025-11-10,ZONE,0.67,0.18,3.17,3.40

In [12]:
# create cols to keep for bulktrans and subtrans circuits
cols_to_keep_bulk = ['Datetime','Date','Master Circuit','Circuit_No', 'FuelsIndex_max_FPI2', 'LFPwtdd_max_FPI2','Max_Wind','Max_Gust']
cols_to_keep_sub = ['Datetime','Date','Master Circuit','Circuit_No', 'FuelsIndex_max_FPI2', 'LFPwtdd_max_FPI2','Max_Wind','Max_Gust']
# concat bulktrans_df with forecast_file_group_bulktrans
bulktrans_df_with_forecast = pd.concat([bulktrans_df[cols_to_keep_bulk], forecast_file_group_bulktrans[cols_to_keep_bulk]], ignore_index=True)
# save file to BulkTrans_Forecast_2025.csv
bulktrans_df_with_forecast.to_csv('//sce.eix.com/workgroup/SPE_DSA/Charles/IgnitionGoalSettingMidput/BulkTrans_Forecasts_2025.csv', index=False)
# concat subtrans_df with forecast_file_group_subtrans
subtrans_df_with_forecast = pd.concat([sub_df[cols_to_keep_sub], forecast_file_group_subtrans[cols_to_keep_sub]], ignore_index=True)
# save file to SubTrans_Forecast_2025.csv
subtrans_df_with_forecast.to_csv('//sce.eix.com/workgroup/SPE_DSA/Charles/IgnitionGoalSettingMidput/SubTrans_Forecasts_2025.csv', index=False)

In [13]:
bulktrans_df

,Datetime,Circuit,Circuit_No,Master Circuit,Segment_Nu,District,County,Substation,Voltage,Wind_Threshold,...,DFM1hr_max_FPI2,DFM10hr_max_FPI2,DFM100hr_max_FPI2,DFM1000hr_max_FPI2,LFM_max_FPI2,NDVI_max_FPI2,FuelsIndex_max_FPI2,LFPwtdd_max_FPI2,FPI2_Thresholds,Date
0,2024-12-31 12:00:00,ANTELOPE-MAGUNDEN NO.1_50,ET-04676,ANTELOPE-MAGUNDEN NO.1,50,52,Kern,ANTELOPE,220.0,40.0,...,0.20,0.21,0.23,0.18,0.75,0.37,0.07,0.12,NaN,2025-01-01
1,2024-12-31 15:00:00,ANTELOPE-MAGUNDEN NO.1_50,ET-04676,ANTELOPE-MAGUNDEN NO.1,50,52,Kern,ANTELOPE,220.0,40.0,...,0.17,0.18,0.22,0.18,0.75,0.37,0.09,0.09,NaN,2025-01-01
2,2024-12-31 18:00:00,ANTELOPE-MAGUNDEN NO.1_50,ET-04676,ANTELOPE-MAGUNDEN NO.1,50,52,Kern,ANTELOPE,220.0,40.0,...,0.16,0.16,0.20,0.20,0.71,0.47,0.09,0.07,NaN,2025-01-01
3,2024-12-31 21:00:00,ANTELOPE-MAGUNDEN NO.1_50,ET-04676,ANTELOPE-MAGUNDEN NO.1,50,52,Kern,ANTELOPE,220.0,40.0,...,0.19,0.18,0.23,0.18,0.82,0.40,0.07,0.19,NaN,2025-01-01
4,2025-01-01 00:00:00,ANTELOPE-MAGUNDEN NO.1_50,ET-04676,ANTELOPE-MAGUNDEN NO.1,50,52,Kern,ANTELOPE,220.0,40.0,...,0.16,0.18,0.22,0.18,0.82,0.40,0.08,0.13,NaN,2025-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4668725,2025-07-21 12:00:00,VINCENT-WINDSTAR 1_153,ET-00153,VINCENT-WINDSTAR 1,153,36,Los Angeles,VINCENT,220.0,40.0,...,0.06,0.07,0.09,0.08,0.67,0.23,0.93,5.82,NaN,2025-07-15
4668726,2025-07-21 15:00:00,VINCENT-WINDSTAR 1_153,ET-00153,VINCENT-WINDSTAR 1,153,36,Los Angeles,VINCENT,220.0,40.0,...,0.05,0.05,0.09,0.08,0.67,0.23,0.94,9.51,NaN,2025-07-15
4668727,2025-07-21 18:00:00,VINCENT-WINDSTAR 1_153,ET-00153,VINCENT-WINDSTAR 1,153,36,Los Angeles,VINCENT,220.0,40.0,...,0.05,0.05,0.09,0.08,0.67,0.23,0.94,8.83,NaN,2025-07-15
4668728,2025-07-21 21:00:00,VINCENT-WINDSTAR 1_153,ET-00153,VINCENT-WINDSTAR 1,153,36,Los Angeles,VINCENT,220.0,40.0,...,0.06,0.05,0.09,0.08,0.67,0.23,0.93,3.76,NaN,2025-07-15
4668729,2025-07-22 00:00:00,VINCENT-WINDSTAR 1_153,ET-00153,VINCENT-WINDSTAR 1,153,36,Los Angeles,VINCENT,220.0,40.0,...,0.14,0.08,0.10,0.09,0.67,0.23,0.88,0.63,NaN,2025-07-15

In [14]:
# # save dist_df to csv
# dist_df.to_csv('CircuitLevelData/Dist_Forecasts_2025.csv', index=False)

In [15]:
# save the DataFrame to a CSV file
# forecast_circuit_2025.to_csv("CircuitLevelData/Forecast_Circuit_20250715.csv", index=False)